import environment from "./environment";

export const AppUrls = {
  GetCurrentUser: `${environment.appUrlPrefix}/User/Current`,
  GetNavigationItems: `${environment.appUrlPrefix}/Navigation`,
  GetAppPages: `${environment.appUrlPrefix}Page`,
  CreateAppPage: `${environment.appUrlPrefix}Page`,
  UpdateAppPage: `${environment.appUrlPrefix}Page`,
  DeleteAppPage: `${environment.appUrlPrefix}Page/{id}`,
  GetAppFunctions: `${environment.appUrlPrefix}Permissions/Functions/{pageId}`,
  CreateAppFunction: `${environment.appUrlPrefix}Permissions/Functions`,
  UpdateAppFunction: `${environment.appUrlPrefix}Permissions/Function`,
  DeleteAppFunction: `${environment.appUrlPrefix}Permissions/Function/{functionId}`,
  GetUserPermittedAppFunctionsFor: `${environment.appUrlPrefix}Permissions/User/{userId}`,
  GetGroupFunctionPermissions: `${environment.appUrlPrefix}Permissions/Group/{groupId}`,
  GetFunctionGroupPermissions: `${environment.appUrlPrefix}Permissions/Page/{pageId}`,
  AddGroupFunctionPermission: `${environment.appUrlPrefix}Permissions/Group/{groupId}/Function/{pfId}`,
  DeleteGroupFunctionPermission: `${environment.appUrlPrefix}Permissions/Group/{groupId}/Function/{pfId}`,
  GetCurrentUserGroups: `${environment.appUrlPrefix}Security/User/Groups`,
  GetAllMenuItems: `${environment.appUrlPrefix}Navigation`,
  AddMenuItem: `${environment.appUrlPrefix}Navigation`,
  UpdateMenuItem: `${environment.appUrlPrefix}Navigation`,
  DeleteMenuItem: `${environment.appUrlPrefix}Navigation/{id}`,
  GetUserInfoById: `${environment.appUrlPrefix}Security/User/{id}`,
  GetAllUsersInfo: `${environment.appUrlPrefix}Security/Users`,
  AddUserInfo: `${environment.appUrlPrefix}Security/User`,
  UpdateUserInfo: `${environment.appUrlPrefix}Security/User`,
  DeleteUserInfo: `${environment.appUrlPrefix}Security/User/{id}`,
  GetAllUserGroups: `${environment.appUrlPrefix}Security/Groups`,
  GetUserGroupById: `${environment.appUrlPrefix}Security/Group/{id}`,
  AddUserGroup: `${environment.appUrlPrefix}Security/Group`,
  UpdateUserGroup: `${environment.appUrlPrefix}Security/Group`,
  DeleteUserGroup: `${environment.appUrlPrefix}Security/Group/{id}`,
  AssociateUserToGroup: `${environment.appUrlPrefix}Security/User/{userId}/Group/{groupId}`,
  DissociateUserToGroup: `${environment.appUrlPrefix}Security/User/{userId}/Group/{groupId}`,
  GetAllUsersInGroup: `${environment.appUrlPrefix}Security/Group/{groupId}/Users`,
  GetAllGroupsForUser: `${environment.appUrlPrefix}Security/User/{userId}/Groups`
};
